# Generated by Django 5.2.8 on 2025-11-19 00:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccion',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='id_cli',
        ),
        migrations.AddField(
            model_name='cliente',
            name='correo',
            field=models.EmailField(default='cliente@ejemplo.com', max_length=100, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='id_Cliente',
            field=models.AutoField(db_column='id_Cliente', primary_key=True, serialize=False, verbose_name='ID Cliente'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nit',
            field=models.CharField(help_text='NIT, RUC o documento de identificación', max_length=20, unique=True, verbose_name='NIT'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(help_text='Nombre completo del cliente o empresa', max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El teléfono debe tener entre 9 y 15 dígitos.', regex='^\\+?1?\\d{9,15}$')], verbose_name='Teléfono'),
        ),
    ]
