# Generated by Django 5.2.8 on 2025-11-19 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'ordering': ['nombres', 'apellidos'], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='cedula',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='clave',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='email',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='id_usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='ultima_conexion',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='apellidos',
            field=models.CharField(default='Sin apellido', help_text='Apellidos completos del usuario', max_length=50, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='correo',
            field=models.EmailField(default='usuario@ejemplo.com', max_length=100, unique=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.IntegerField(blank=True, help_text='Número de identificación (Cédula, TI, etc.)', null=True, unique=True, verbose_name='Documento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_usu',
            field=models.AutoField(db_column='id_usu', primary_key=True, serialize=False, verbose_name='ID Usuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='nombres',
            field=models.CharField(default='Sin nombre', help_text='Nombres completos del usuario', max_length=50, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='password',
            field=models.CharField(default='sin_password', max_length=256, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='direccion',
            field=models.CharField(default='Sin dirección', max_length=100, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.BigIntegerField(default=0, verbose_name='Teléfono'),
        ),
    ]
