# Generated by Django 5.2.8 on 2025-11-19 00:47

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_detalleinsumo_options_and_more'),
        ('recetas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='nombre',
            field=models.CharField(default='Producto sin nombre', help_text='Nombre del producto o plato', max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='receta',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de venta del producto', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=3, default=Decimal('1.000'), help_text='Cantidad del insumo necesaria para esta receta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='unidad',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('unidad', 'Unidades'), ('cucharada', 'Cucharadas'), ('cucharadita', 'Cucharaditas'), ('taza', 'Tazas'), ('pizca', 'Pizca')], default='kg', max_length=15, verbose_name='Unidad de medida'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['estado'], name='recetas_estado_92ca33_idx'),
        ),
        migrations.AddIndex(
            model_name='receta',
            index=models.Index(fields=['nombre'], name='recetas_nombre_0585c9_idx'),
        ),
        migrations.AddIndex(
            model_name='recetainsumo',
            index=models.Index(fields=['estado'], name='receta_insu_estado_ee8338_idx'),
        ),
        migrations.AddIndex(
            model_name='recetainsumo',
            index=models.Index(fields=['receta', 'insumo'], name='receta_insu_id_rec_09ca39_idx'),
        ),
    ]
