# Generated by Django 5.2.7 on 2025-11-20 16:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_nombre_alter_receta_precio_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recetainsumo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='recetainsumo',
            name='fecha_modificacion',
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad del insumo necesaria para esta receta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad'),
        ),
        migrations.AlterField(
            model_name='recetainsumo',
            name='unidad',
            field=models.CharField(choices=[('g', 'Gramos'), ('kg', 'Kilogramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('unidad', 'Unidades'), ('cucharada', 'Cucharadas'), ('cucharadita', 'Cucharaditas'), ('taza', 'Tazas'), ('pizca', 'Pizca')], default='kg', max_length=20, verbose_name='Unidad de medida'),
        ),
    ]
