# Generated by Django 5.2.8 on 2025-11-19 00:47

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleinsumo',
            options={'ordering': ['fecha_vencimiento', '-fecha_ingreso'], 'verbose_name': 'Detalle de Insumo', 'verbose_name_plural': 'Detalles de Insumos'},
        ),
        migrations.RemoveField(
            model_name='detalleinsumo',
            name='cantidad_actual',
        ),
        migrations.RemoveField(
            model_name='detalleinsumo',
            name='cantidad_lote',
        ),
        migrations.RemoveField(
            model_name='detalleinsumo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='detalleinsumo',
            name='id_det_ins',
        ),
        migrations.RemoveField(
            model_name='detalleinsumo',
            name='insumo',
        ),
        migrations.RemoveField(
            model_name='detalleinsumo',
            name='numero_lote',
        ),
        migrations.RemoveField(
            model_name='detalleinsumo',
            name='precio_compra',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='descripcion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='precio_unitario',
        ),
        migrations.RemoveField(
            model_name='insumo',
            name='stock_minimo',
        ),
        migrations.AddField(
            model_name='detalleinsumo',
            name='cantidad',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad del lote', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='detalleinsumo',
            name='id_detalle',
            field=models.AutoField(db_column='id_detalle', primary_key=True, serialize=False, verbose_name='ID Detalle'),
        ),
        migrations.AddField(
            model_name='detalleinsumo',
            name='id_ins',
            field=models.ForeignKey(db_column='id_ins', default=2, help_text='Insumo al que pertenece este lote', on_delete=django.db.models.deletion.CASCADE, to='insumos.insumo', verbose_name='Insumo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='insumo',
            name='stock_min',
            field=models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad mínima requerida en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Mínimo'),
        ),
        migrations.AlterField(
            model_name='detalleinsumo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Vencido', 'Vencido'), ('Agotado', 'Agotado'), ('Eliminado', 'Eliminado')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='detalleinsumo',
            name='fecha_ingreso',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de ingreso del lote', verbose_name='Fecha de Ingreso'),
        ),
        migrations.AlterField(
            model_name='detalleinsumo',
            name='fecha_vencimiento',
            field=models.DateField(blank=True, help_text='Fecha de vencimiento del lote (opcional)', null=True, verbose_name='Fecha de Vencimiento'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo'), ('Stock insuficiente', 'Stock insuficiente')], default='Activo', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='nombre',
            field=models.CharField(default='Insumo sin nombre', help_text='Nombre del insumo', max_length=45, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='stock_actual',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad actual en inventario', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Actual'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('unidad', 'Unidades'), ('lb', 'Libras'), ('oz', 'Onzas')], default='kg', max_length=10, verbose_name='Unidad de Medida'),
        ),
        migrations.AddIndex(
            model_name='detalleinsumo',
            index=models.Index(fields=['estado'], name='detalle_ins_estado_f0821b_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleinsumo',
            index=models.Index(fields=['fecha_vencimiento'], name='detalle_ins_fecha_v_cc2862_idx'),
        ),
        migrations.AddIndex(
            model_name='detalleinsumo',
            index=models.Index(fields=['id_ins', 'estado'], name='detalle_ins_id_ins_af0735_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['estado'], name='insumos_estado_7ca5f5_idx'),
        ),
        migrations.AddIndex(
            model_name='insumo',
            index=models.Index(fields=['nombre'], name='insumos_nombre_f9a344_idx'),
        ),
        migrations.AlterModelTable(
            name='detalleinsumo',
            table='detalle_insumo',
        ),
    ]
