# Generated by Django 5.2.8 on 2025-11-19 02:02

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0002_alter_detalleinsumo_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialInsumo',
            fields=[
                ('id_hist', models.AutoField(db_column='idHist', primary_key=True, serialize=False, verbose_name='ID Historial')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la operación', verbose_name='Fecha')),
                ('accion', models.CharField(choices=[('Ingreso', 'Ingreso de Mercancía'), ('Salida', 'Salida por Producción'), ('Ajuste', 'Ajuste de Inventario'), ('Vencimiento', 'Producto Vencido'), ('Merma', 'Merma o Pérdida'), ('Devolución', 'Devolución'), ('Transferencia', 'Transferencia'), ('Creación', 'Creación de Insumo'), ('Actualización', 'Actualización de Datos')], help_text='Tipo de operación realizada', max_length=20, verbose_name='Acción')),
                ('estado', models.CharField(default='Activo', help_text='Estado del insumo después de la operación', max_length=20, verbose_name='Estado')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Cantidad involucrada en la operación', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Cantidad')),
                ('stock_actual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Stock total después de la operación', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Stock Actual')),
                ('novedad', models.TextField(blank=True, help_text='Descripción detallada de la operación o novedad', null=True, verbose_name='Novedad')),
                ('detalle_insumo', models.ForeignKey(blank=True, db_column='id_detalle', help_text='Lote específico afectado (si aplica)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='insumos.detalleinsumo', verbose_name='Detalle de Insumo')),
                ('insumo', models.ForeignKey(db_column='id_ins', help_text='Insumo afectado por la operación', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='insumos.insumo', verbose_name='Insumo')),
            ],
            options={
                'verbose_name': 'Historial de Insumo',
                'verbose_name_plural': 'Historiales de Insumos',
                'db_table': 'historial',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['fecha'], name='historial_fecha_be8353_idx'), models.Index(fields=['accion'], name='historial_accion_f86488_idx'), models.Index(fields=['insumo'], name='historial_id_ins_838efa_idx'), models.Index(fields=['insumo', 'fecha'], name='historial_id_ins_354196_idx'), models.Index(fields=['detalle_insumo'], name='historial_id_deta_bc8d11_idx')],
            },
        ),
    ]
