# Generated by Django 5.2.7 on 2025-11-19 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_historialinsumo'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historialinsumo',
            name='historial_id_deta_bc8d11_idx',
        ),
        migrations.RemoveField(
            model_name='historialinsumo',
            name='detalle_insumo',
        ),
        migrations.AddField(
            model_name='historialinsumo',
            name='id_detalle',
            field=models.IntegerField(blank=True, help_text='ID del lote específico afectado', null=True, verbose_name='ID Detalle'),
        ),
        migrations.AddIndex(
            model_name='historialinsumo',
            index=models.Index(fields=['id_detalle'], name='historial_id_deta_bc8d11_idx'),
        ),
    ]
