mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `clientes` (`id_Cliente`, `nombre`, `nit`, `telefono`, `correo`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `detalle_insumo` (`id_detalle`, `id_ins`, `cantidad`, `fecha_ingreso`, `fecha_vencimiento`, `estado`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `historial` (`idHist`, `fecha`, `accion`, `estado`, `cantidad`, `stock_actual`, `novedad`, `id_ins`, `id_detalle`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `insumos` (`id_ins`, `nombre`, `unidad_medida`, `stock_min`, `stock_actual`, `estado`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `pago` (`id_pago`, `id_ven`, `fecha_pago`, `monto`, `tipo_pago`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `produccion` (`id_proc`, `estado`, `fecha_hora`, `fecha_aceptacion`, `fecha_finalizacion`, `id_usu`, `id_asignado`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `produccion_recetas` (`id_detalle`, `id_produccion`, `id_rec`, `cantidad`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `recetas` (`id_rec`, `nombre`, `descripcion`, `precio`, `estado`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `receta_insumos` (`id_rec_ins`, `id_rec`, `id_ins`, `cantidad`, `unidad`, `estado`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `usuarios` (`id_usu`, `documento`, `nombres`, `apellidos`, `telefono`, `direccion`, `correo`, `rol`, `estado`, `password`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `ventas` (`id_ven`, `Tipo`, `fecha`, `id_usu`, `id_asignado`, `id_Cliente`, `total`, `estado`, `observaciones`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `venta_produccion` (`id_ven_prod`, `id_venta`, `id_produccion`, `cantidad`) VALUES"
mysql -u root -h 127.0.0.1 -P 3306 pae -e "INSERT INTO `venta_recetas` (`id_venta_receta`, `id_venta`, `id_receta`, `cantidad`, `precio`, `subtotal`) VALUES"
