# Generated by Django 4.2.26 on 2025-11-19 01:54

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recetas', '0002_alter_receta_nombre_alter_receta_precio_and_more'),
        ('usuarios', '0002_alter_usuario_options_remove_usuario_activo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('id_proc', models.AutoField(db_column='id_proc', primary_key=True, serialize=False, verbose_name='ID Producción')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Asignada', 'Asignada'), ('En Proceso', 'En Proceso'), ('Finalizada', 'Finalizada'), ('Cancelada', 'Cancelada')], default='Pendiente', help_text='Estado actual de la orden de producción', max_length=20, verbose_name='Estado')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, help_text='Cuando se creó la orden de producción', verbose_name='Fecha y Hora de Creación')),
                ('fecha_aceptacion', models.DateTimeField(blank=True, help_text='Cuando el empleado aceptó la orden', null=True, verbose_name='Fecha de Aceptación')),
                ('fecha_finalizacion', models.DateTimeField(blank=True, help_text='Cuando se completó la producción', null=True, verbose_name='Fecha de Finalización')),
                ('cantidad', models.DecimalField(decimal_places=2, default=Decimal('1.00'), help_text='Cantidad de productos a producir', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Cantidad')),
                ('receta', models.ForeignKey(db_column='idReceta', help_text='Producto/receta a producir', on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='recetas.receta', verbose_name='Receta')),
                ('usuario_asignado', models.ForeignKey(db_column='id_asignado', help_text='Empleado de producción asignado', limit_choices_to={'rol': 'EP'}, on_delete=django.db.models.deletion.CASCADE, related_name='producciones_asignadas', to='usuarios.usuario', verbose_name='Usuario Asignado')),
                ('usuario_creador', models.ForeignKey(db_column='id_usu', help_text='Usuario que creó la orden de producción', on_delete=django.db.models.deletion.CASCADE, related_name='producciones_creadas', to='usuarios.usuario', verbose_name='Usuario Creador')),
            ],
            options={
                'verbose_name': 'Producción',
                'verbose_name_plural': 'Producciones',
                'db_table': 'produccion',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['estado'], name='produccion_estado_75f755_idx'), models.Index(fields=['fecha_hora'], name='produccion_fecha_h_d514af_idx'), models.Index(fields=['usuario_asignado', 'estado'], name='produccion_id_asig_9d5a5d_idx'), models.Index(fields=['receta'], name='produccion_idRecet_72879a_idx')],
            },
        ),
    ]
