# Generated by Django 5.2.8 on 2025-11-19 02:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
        ('recetas', '0002_alter_receta_nombre_alter_receta_precio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProduccionReceta',
            fields=[
                ('id_detalle', models.AutoField(db_column='id_detalle', primary_key=True, serialize=False, verbose_name='ID Detalle')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos a producir', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('produccion', models.ForeignKey(db_column='id_produccion', help_text='Orden de producción a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_recetas', to='produccion.produccion', verbose_name='Orden de Producción')),
                ('receta', models.ForeignKey(db_column='id_rec', help_text='Receta/producto a producir', on_delete=django.db.models.deletion.CASCADE, related_name='detalles_produccion', to='recetas.receta', verbose_name='Receta/Producto')),
            ],
            options={
                'verbose_name': 'Detalle de Producción',
                'verbose_name_plural': 'Detalles de Producción',
                'db_table': 'produccion_recetas',
                'ordering': ['produccion', 'id_detalle'],
                'indexes': [models.Index(fields=['produccion'], name='produccion__id_prod_95bdf8_idx'), models.Index(fields=['receta'], name='produccion__id_rec_256367_idx'), models.Index(fields=['produccion', 'receta'], name='produccion__id_prod_25bd3e_idx')],
                'unique_together': {('produccion', 'receta')},
            },
        ),
    ]
