# Generated by Django 4.2.26 on 2025-11-19 01:56

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produccion', '0001_initial'),
        ('usuarios', '0002_alter_usuario_options_remove_usuario_activo_and_more'),
        ('clientes', '0002_remove_cliente_direccion_remove_cliente_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id_ven', models.AutoField(db_column='idVen', primary_key=True, serialize=False, verbose_name='ID Venta')),
                ('tipo', models.CharField(choices=[('Directa', 'Venta Directa'), ('Produccion', 'Venta por Producción'), ('Mayorista', 'Venta Mayorista'), ('Minorista', 'Venta Minorista')], default='Directa', help_text='Tipo de venta realizada', max_length=20, verbose_name='Tipo de Venta')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Valor total de la venta', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Total')),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('En Preparacion', 'En Preparación'), ('Lista', 'Lista para Entrega'), ('Entregada', 'Entregada'), ('Cancelada', 'Cancelada'), ('Facturada', 'Facturada')], default='Pendiente', help_text='Estado actual de la venta', max_length=20, verbose_name='Estado')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora de la venta', verbose_name='Fecha')),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones adicionales sobre la venta', null=True, verbose_name='Observaciones')),
                ('cliente', models.ForeignKey(db_column='idCliente', help_text='Cliente que realiza la compra', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='clientes.cliente', verbose_name='Cliente')),
                ('numero_produccion', models.ForeignKey(blank=True, db_column='numeroProduccion', help_text='Producción asociada a esta venta (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ventas', to='produccion.produccion', verbose_name='Número de Producción')),
                ('usuario', models.ForeignKey(db_column='idUsuario', help_text='Usuario que registra la venta', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_registradas', to='usuarios.usuario', verbose_name='Usuario')),
                ('usuario_asignado', models.ForeignKey(db_column='idAsignado', help_text='Usuario asignado para procesar la venta', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_asignadas', to='usuarios.usuario', verbose_name='Usuario Asignado')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha'],
                'indexes': [models.Index(fields=['estado'], name='ventas_estado_505824_idx'), models.Index(fields=['fecha'], name='ventas_fecha_b4b2af_idx'), models.Index(fields=['cliente'], name='ventas_idClien_dfbf9a_idx'), models.Index(fields=['tipo'], name='ventas_tipo_a54548_idx'), models.Index(fields=['usuario_asignado', 'estado'], name='ventas_idAsign_8e7a3f_idx')],
            },
        ),
    ]
