# Generated by Django 5.2.8 on 2025-11-19 02:05

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(db_column='idPago', primary_key=True, serialize=False, verbose_name='ID Pago')),
                ('fecha_pago', models.DateTimeField(default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó el pago', verbose_name='Fecha de Pago')),
                ('monto', models.DecimalField(decimal_places=2, help_text='Monto del pago realizado', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto')),
                ('tipo_pago', models.CharField(choices=[('abono', 'Abono Parcial'), ('total', 'Pago Total'), ('inicial', 'Pago Inicial'), ('final', 'Pago Final'), ('único', 'Pago Único')], default='abono', help_text='Indica si es un abono parcial o pago total', max_length=20, verbose_name='Tipo de Pago')),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta_credito', 'Tarjeta de Crédito'), ('tarjeta_debito', 'Tarjeta de Débito'), ('transferencia', 'Transferencia Bancaria'), ('cheque', 'Cheque'), ('nequi', 'Nequi'), ('daviplata', 'Daviplata'), ('otro', 'Otro')], default='efectivo', help_text='Forma de pago utilizada', max_length=20, verbose_name='Método de Pago')),
                ('observaciones', models.TextField(blank=True, help_text='Notas adicionales sobre el pago', null=True, verbose_name='Observaciones')),
                ('venta', models.ForeignKey(db_column='id_ven', help_text='Venta a la que pertenece este pago', on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pago',
                'ordering': ['-fecha_pago'],
                'indexes': [models.Index(fields=['fecha_pago'], name='pago_fecha_p_e0ee42_idx'), models.Index(fields=['venta'], name='pago_id_ven_af3331_idx'), models.Index(fields=['tipo_pago'], name='pago_tipo_pa_3bb066_idx'), models.Index(fields=['metodo_pago'], name='pago_metodo__d019a7_idx'), models.Index(fields=['venta', 'fecha_pago'], name='pago_id_ven_329fcd_idx')],
            },
        ),
    ]
