# Generated by Django 5.2.8 on 2025-11-19 02:08

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_nombre_alter_receta_precio_and_more'),
        ('ventas', '0002_pago'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id_detalle', models.AutoField(db_column='idDetalle', primary_key=True, serialize=False, verbose_name='ID Detalle')),
                ('nombre_empanada', models.CharField(blank=True, help_text='Nombre del producto al momento de la venta (histórico)', max_length=100, verbose_name='Nombre del Producto')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos vendidos', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio por unidad al momento de la venta (histórico)', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio Unitario')),
                ('receta', models.ForeignKey(db_column='id_receta', help_text='Producto vendido', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_detalle', to='recetas.receta', verbose_name='Receta/Producto')),
                ('venta', models.ForeignKey(db_column='id_ven', help_text='Venta a la que pertenece este detalle', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalle_venta',
                'ordering': ['venta', 'id_detalle'],
                'indexes': [models.Index(fields=['venta'], name='detalle_ven_id_ven_1c1eeb_idx'), models.Index(fields=['receta'], name='detalle_ven_id_rece_722eda_idx'), models.Index(fields=['venta', 'receta'], name='detalle_ven_id_ven_42c6ce_idx')],
                'unique_together': {('venta', 'receta')},
            },
        ),
    ]
