# Generated by Django 5.2.8 on 2025-11-19 02:21

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_produccionreceta'),
        ('ventas', '0003_detalleventa'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaProduccion',
            fields=[
                ('id_ven_prod', models.AutoField(db_column='idVenProd', primary_key=True, serialize=False, verbose_name='ID Venta-Producción')),
                ('cantidad', models.IntegerField(help_text='Cantidad de productos asociados entre la venta y producción', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('nombre_produccion', models.CharField(blank=True, help_text='Nombre descriptivo de la producción (histórico)', max_length=200, verbose_name='Nombre Producción')),
                ('nombre_venta', models.CharField(blank=True, help_text='Nombre descriptivo de la venta (histórico)', max_length=200, verbose_name='Nombre Venta')),
                ('produccion', models.ForeignKey(db_column='idProduccion', help_text='Orden de producción asociada', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_asociadas', to='produccion.produccion', verbose_name='Producción')),
                ('venta', models.ForeignKey(db_column='idVenta', help_text='Venta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='producciones_asociadas', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Venta-Producción',
                'verbose_name_plural': 'Ventas-Producciones',
                'db_table': 'venta_produccion',
                'ordering': ['venta', 'produccion'],
                'indexes': [models.Index(fields=['venta'], name='venta_produ_idVenta_f1fa42_idx'), models.Index(fields=['produccion'], name='venta_produ_idProdu_2635a8_idx'), models.Index(fields=['venta', 'produccion'], name='venta_produ_idVenta_57acfe_idx')],
                'unique_together': {('venta', 'produccion')},
            },
        ),
    ]
