# Generated by Django 5.2.8 on 2025-11-19 02:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recetas', '0002_alter_receta_nombre_alter_receta_precio_and_more'),
        ('ventas', '0004_ventaproduccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='VentaReceta',
            fields=[
                ('id_venta_receta', models.AutoField(db_column='idVentaReceta', primary_key=True, serialize=False, verbose_name='ID Venta-Receta')),
                ('cantidad', models.IntegerField(help_text='Cantidad de recetas vendidas', validators=[django.core.validators.MinValueValidator(1)], verbose_name='Cantidad')),
                ('precio', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de la receta al momento de la venta', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Precio')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Subtotal calculado (cantidad × precio)', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Subtotal')),
                ('nombre_receta', models.CharField(blank=True, help_text='Nombre de la receta al momento de la venta (histórico)', max_length=200, verbose_name='Nombre Receta')),
                ('nombre_venta', models.CharField(blank=True, help_text='Identificación de la venta (histórico)', max_length=200, verbose_name='Nombre Venta')),
                ('receta', models.ForeignKey(db_column='idReceta', help_text='Receta vendida', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_asociadas', to='recetas.receta', verbose_name='Receta')),
                ('venta', models.ForeignKey(db_column='idVenta', help_text='Venta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='recetas_asociadas', to='ventas.venta', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Venta-Receta',
                'verbose_name_plural': 'Ventas-Recetas',
                'db_table': 'venta_recetas',
                'ordering': ['venta', 'receta'],
                'indexes': [models.Index(fields=['venta'], name='venta_recet_idVenta_414f63_idx'), models.Index(fields=['receta'], name='venta_recet_idRecet_e1829b_idx'), models.Index(fields=['venta', 'receta'], name='venta_recet_idVenta_d7f933_idx'), models.Index(fields=['precio'], name='venta_recet_precio_acca6f_idx'), models.Index(fields=['cantidad'], name='venta_recet_cantida_adcafb_idx')],
                'unique_together': {('venta', 'receta')},
            },
        ),
    ]
