# Generated by Django 5.2.7 on 2025-11-22 21:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_remove_cliente_direccion_remove_cliente_email_and_more'),
        ('recetas', '0003_remove_recetainsumo_fecha_creacion_and_more'),
        ('usuarios', '0002_alter_usuario_options_remove_usuario_activo_and_more'),
        ('ventas', '0005_ventareceta'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='pago',
            name='pago_metodo__d019a7_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_id_Clie_6f3074_idx',
            old_name='ventas_idClien_dfbf9a_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_Tipo_ef3d64_idx',
            old_name='ventas_tipo_a54548_idx',
        ),
        migrations.RenameIndex(
            model_name='venta',
            new_name='ventas_id_asig_5a7b4f_idx',
            old_name='ventas_idAsign_8e7a3f_idx',
        ),
        migrations.RenameIndex(
            model_name='ventareceta',
            new_name='venta_recet_id_vent_06b365_idx',
            old_name='venta_recet_idVenta_414f63_idx',
        ),
        migrations.RenameIndex(
            model_name='ventareceta',
            new_name='venta_recet_id_rece_98e187_idx',
            old_name='venta_recet_idRecet_e1829b_idx',
        ),
        migrations.RenameIndex(
            model_name='ventareceta',
            new_name='venta_recet_id_vent_2ddd1b_idx',
            old_name='venta_recet_idVenta_d7f933_idx',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='metodo_pago',
        ),
        migrations.RemoveField(
            model_name='pago',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='numero_produccion',
        ),
        migrations.RemoveField(
            model_name='ventareceta',
            name='nombre_receta',
        ),
        migrations.RemoveField(
            model_name='ventareceta',
            name='nombre_venta',
        ),
        migrations.AlterField(
            model_name='pago',
            name='fecha_pago',
            field=models.DateTimeField(db_column='fecha_pago', default=django.utils.timezone.now, help_text='Fecha y hora en que se realizó el pago', verbose_name='Fecha de Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='id_pago',
            field=models.AutoField(db_column='id_pago', primary_key=True, serialize=False, verbose_name='ID Pago'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='monto',
            field=models.DecimalField(db_column='monto', decimal_places=2, help_text='Monto del pago realizado', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo_pago',
            field=models.CharField(choices=[('abono', 'Abono'), ('total', 'Pago total')], db_column='tipo_pago', default='abono', help_text='Indica si es un abono parcial o pago total', max_length=20, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cliente',
            field=models.ForeignKey(db_column='id_Cliente', help_text='Cliente que realiza la compra', on_delete=django.db.models.deletion.CASCADE, related_name='ventas', to='clientes.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='estado',
            field=models.CharField(choices=[('Pago pendiente', 'Pago Pendiente'), ('Procesando', 'Procesando'), ('Pago completo', 'Pago Completo'), ('Completada', 'Completada')], default='Pago pendiente', help_text='Estado actual de la venta', max_length=20, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='id_ven',
            field=models.AutoField(db_column='id_ven', primary_key=True, serialize=False, verbose_name='ID Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo',
            field=models.CharField(choices=[('directa', 'Venta Directa'), ('pedido', 'Pedido')], db_column='Tipo', default='directa', help_text='Tipo de venta realizada', max_length=20, verbose_name='Tipo de Venta'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario',
            field=models.ForeignKey(db_column='id_usu', help_text='Usuario que registra la venta', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_registradas', to='usuarios.usuario', verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='usuario_asignado',
            field=models.ForeignKey(blank=True, db_column='id_asignado', help_text='Usuario asignado para procesar la venta', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ventas_asignadas', to='usuarios.usuario', verbose_name='Usuario Asignado'),
        ),
        migrations.AlterField(
            model_name='ventareceta',
            name='id_venta_receta',
            field=models.AutoField(db_column='id_venta_receta', primary_key=True, serialize=False, verbose_name='ID Venta-Receta'),
        ),
        migrations.AlterField(
            model_name='ventareceta',
            name='receta',
            field=models.ForeignKey(db_column='id_receta', help_text='Receta vendida', on_delete=django.db.models.deletion.CASCADE, related_name='ventas_asociadas', to='recetas.receta', verbose_name='Receta'),
        ),
        migrations.AlterField(
            model_name='ventareceta',
            name='venta',
            field=models.ForeignKey(db_column='id_venta', help_text='Venta asociada', on_delete=django.db.models.deletion.CASCADE, related_name='recetas_asociadas', to='ventas.venta', verbose_name='Venta'),
        ),
    ]
